name: Autograding Tests
'on':
  - workflow_dispatch
  - repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Tests and Save Output
        run: python run_test_tofile.py | tee test_output.txt

      - name: Upload test output as artifact
        uses: actions/upload-artifact@v4
        with:
          name: test-output
          path: test_output.txt
