name: Autograding Tests
'on':
- workflow_dispatch
- repository_dispatch

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run Tests and Save Output
      id: test1
      run: python -u run_test.py | tee test_output.txt
      timeout-minutes: 1
      
    - name: Upload Test Output as Artifact
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: test_output.txt
